spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booksdb
    username: postgres
    password: Maclexy1988?

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  graphql:
    graphiql:
      enabled: true
